services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
  auth-service:
    build:
      #context: .
      #dockerfile: ./auth-service/Dockerfile
      context: ./auth-service # specify directory where local Dockerfile is located
